import json
from pathlib import Path

from imperator import engine
from imperator.commands.clean import clean_project
from imperator.commands.doctor import run_doctor
from imperator.config import save_config

REPO_ROOT = Path(__file__).resolve().parents[2]


def test_doctor_reports_missing_config(tmp_path, monkeypatch):
    monkeypatch.setenv("IMPERATOR_DIR", str(REPO_ROOT))

    result = run_doctor(tmp_path)

    assert not result.healthy
    assert ".imperator.json not found" in result.errors


def test_doctor_reports_healthy_fresh_output(tmp_path, monkeypatch):
    monkeypatch.setenv("IMPERATOR_DIR", str(REPO_ROOT))
    save_config("codex", ["python"], ["backend-developer"], "compact", tmp_path)
    engine.compile_project(
        ["python"], ["backend-developer"],
        style="compact", out_dir=tmp_path, agent="codex", root=REPO_ROOT,
    )

    result = run_doctor(tmp_path)

    assert result.healthy
    assert any("Generated output: fresh" in item for item in result.ok)
    assert tmp_path / "AGENTS.md" in result.detected


def test_doctor_reports_stale_output(tmp_path, monkeypatch):
    monkeypatch.setenv("IMPERATOR_DIR", str(REPO_ROOT))
    save_config("gemini", ["python"], [], "compact", tmp_path)
    engine.compile_project(["python"], [], style="compact", out_dir=tmp_path, agent="gemini", root=REPO_ROOT)
    (tmp_path / "GEMINI.md").write_text("<!-- imperator:begin generated -->\nstale\n<!-- imperator:end generated -->\n", encoding="utf-8")

    result = run_doctor(tmp_path)

    assert not result.healthy
    assert tmp_path / "GEMINI.md" in result.stale


def test_doctor_reports_invalid_config_values(tmp_path, monkeypatch):
    monkeypatch.setenv("IMPERATOR_DIR", str(REPO_ROOT))
    (tmp_path / ".imperator.json").write_text(
        json.dumps({"agent": "unknown", "style": "compact", "domains": ["nope"], "roles": []}),
        encoding="utf-8",
    )

    result = run_doctor(tmp_path)

    assert not result.healthy
    assert any("Unsupported agent" in error for error in result.errors)
    assert any("Unknown domain" in error for error in result.errors)


def test_clean_removes_only_generated_files(tmp_path):
    claude = tmp_path / ".claude"
    claude.mkdir()
    generated = claude / "CLAUDE.md"
    generated.write_text("<!-- imperator:begin generated -->\nowned\n<!-- imperator:end generated -->\n", encoding="utf-8")
    user_file = claude / "notes.md"
    user_file.write_text("user notes\n", encoding="utf-8")
    top_level = tmp_path / "AGENTS.md"
    top_level.write_text("<!-- Generated by Imperator v0.3.0 -->\nlegacy\n", encoding="utf-8")

    result = clean_project(tmp_path)

    assert generated in result.removed
    assert top_level in result.removed
    assert user_file in result.skipped
    assert not generated.exists()
    assert not top_level.exists()
    assert user_file.exists()
    assert claude.exists()
