"""Shared rendering helpers and the renderer protocol.

Holds the Jinja environment, rule-block rendering, ownership-marker handling,
the file-write helper, and the `Renderer` base class + `RenderContext` that the
per-target renderers (claude/cursor/codex/gemini) and the compiler use.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape

from ..catalog import MARKER_BEGIN, MARKER_END, VERSION
from ..parser import Role, Rule, RuleGroup

_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"


# ── Jinja environment ────────────────────────────────────────────────────────

def _env() -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(_TEMPLATES_DIR)),
        autoescape=select_autoescape(enabled_extensions=()),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.filters["toml_string"] = json.dumps
    return env


def estimate_tokens(text: str) -> int:
    """Rough heuristic: ~4 characters per token."""
    return max(1, round(len(text) / 4))


# ── Rule rendering ───────────────────────────────────────────────────────────

def _compress_body(body: str, style: str) -> str:
    """Trim a rule body to the requested compression profile.

    standard: verbatim. compact: drop fenced ```code``` blocks (keep directive +
    bullets). strict: keep only the first non-empty line (the directive).
    """
    if style == "standard" or not body:
        return body

    lines = body.split("\n")

    if style == "strict":
        for line in lines:
            if line.strip():
                return line.rstrip()
        return ""

    # compact: strip fenced example blocks
    out: list[str] = []
    in_fence = False
    for line in lines:
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        out.append(line)
    return "\n".join(out).strip("\n")


def render_rule(rule: Rule, style: str) -> str:
    body = _compress_body(rule.body, style)
    head = f"## {rule.id} · {rule.name} · {rule.severity}"
    return f"{head}\n{body}" if body else head


def rules_block(groups: list[RuleGroup], style: str) -> str:
    sections: list[str] = []
    for g in groups:
        rendered = "\n\n".join(render_rule(r, style) for r in g.rules)
        parts = [f"# {g.title}"]
        if g.overview and style != "strict":
            parts.append(g.overview)
        parts.append(rendered)
        sections.append("\n\n".join(parts))
    return "\n\n".join(sections)


# Back-compat private alias (old engine name).
_rules_block = rules_block


def generated_comment(agent: str, style: str) -> str:
    return (f"<!-- Generated by Imperator v{VERSION} for {agent} · "
            f"style: {style} · do not edit by hand -->")


# ── Ownership markers ────────────────────────────────────────────────────────

def has_generated_marker(text: str) -> bool:
    return MARKER_BEGIN in text and MARKER_END in text


def has_legacy_generated_marker(text: str) -> bool:
    return "Generated by Imperator" in text


def is_generated_content(text: str) -> bool:
    return has_generated_marker(text) or has_legacy_generated_marker(text)


def _marker_comments(path: Path) -> tuple[str, str]:
    if path.suffix == ".toml":
        return f"# {MARKER_BEGIN}", f"# {MARKER_END}"
    return f"<!-- {MARKER_BEGIN} -->", f"<!-- {MARKER_END} -->"


def _split_frontmatter(content: str) -> tuple[str, str]:
    if not content.startswith("---\n"):
        return "", content
    end = content.find("\n---", 4)
    if end == -1:
        return "", content
    after = end + len("\n---")
    if after < len(content) and content[after] == "\n":
        after += 1
    return content[:after], content[after:]


def add_generated_markers(path: Path, content: str) -> str:
    """Wrap generated content in ownership markers without breaking frontmatter."""
    if has_generated_marker(content):
        return content
    begin, end = _marker_comments(path)
    prefix, body = _split_frontmatter(content)
    body = body.strip("\n")
    return f"{prefix}{begin}\n{body}\n{end}\n"


def write_file(path: Path, content: str, written: list[Path]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(add_generated_markers(path, content), encoding="utf-8")
    written.append(path)


# ── Shared module renderers (used by codex/gemini, and cursor roles) ──────────

def render_markdown_rule_module(groups: list[RuleGroup], style: str,
                                agent: str, title: str) -> str:
    body = rules_block(groups, style)
    return f"{generated_comment(agent, style)}\n# {title}\n\n{body}\n"


def role_instruction_doc(role: Role, global_groups: list[RuleGroup],
                         domain_groups: list[RuleGroup], style: str,
                         agent: str) -> str:
    """A self-contained role instruction document: persona + global + active domains."""
    active = [g for g in domain_groups if g.source in role.domains]
    global_block = rules_block(global_groups, style)
    domain_block = rules_block(active, style)
    parts = [
        generated_comment(agent, style),
        role.body,
        "Imperator global rules and active domain rules are embedded below. "
        "Follow them for all delegated work.",
        "# Imperator Global Rules",
        global_block,
    ]
    if domain_block:
        suffix = f" ({', '.join(g.source for g in active)})" if active else ""
        parts.extend([f"# Active Domain Rules{suffix}", domain_block])
    return "\n\n".join(parts).strip() + "\n"


# Back-compat private alias (old engine name).
_role_instruction_doc = role_instruction_doc


# ── Renderer protocol ────────────────────────────────────────────────────────

@dataclass
class RenderContext:
    """Everything a renderer needs to emit one project's native layout."""
    out_dir: Path
    domains: list[str]               # selected domain names (selection order)
    roles: list[str]                 # selected role names
    role_defs: list[Role]            # loaded Role objects
    global_groups: list[RuleGroup]   # agent-filtered global rule groups
    domain_groups: list[RuleGroup]   # agent-filtered domain rule groups
    style: str


class Renderer:
    """Base class for per-agent native-layout renderers."""

    agent: str = ""

    def compile(self, ctx: RenderContext) -> list[Path]:  # pragma: no cover - abstract
        raise NotImplementedError
